### PR TITLE
WIP: Don't require any-taps to be git repos

### PR DESCRIPTION
**Pull request by chdiza**
Addresses #10.

### CODE REVIEW

**Comment by chdiza** [comment]
I haven't yet started working on `any-untap` yet.  I figure I'd wait to see how `any-tap` shakes out.

**Comment by telemachus** [comment]
A few thoughts/questions:

+ Should we allow `wget` in addition to `curl`? Kinder to the user, but more work for us. (They have different behavior and flags, for example.)
+ I'd love to get rid of the extra flags `--rsync`, etc. We could switch on the URL, except that `curl`, `wget` *and* `git` can handle HTTP(S).
+ As far as I know, `curl` cannot download a directory, but `wget` can. http://superuser.com/questions/200426/curl-to-download-a-directory
+ For the moment, I'm definitely going to pull the change to update `brew any-tap`, and I'll add you to the contributors.

**Comment by telemachus** [comment]
Ok, sorry, but upon further thought, I'm inclined to sunset `brew anytap` right now. In a nutshell, I can't quite see the point of maintaining this simply in order to track changes to `brew tap` since that command now does essentially everything that `brew any-tap` does.

I still like your idea of non-git directories, but I think you should go about it slightly differently:

1. Propose the big idea (allowing non-git directories to be tapped).
1. If that goes through, then create a new external command (`brew sync`, `brew copy`, whatever), that supports `rsync`, `cp`, `ln`, etc.

Does that make sense to you? I'm going to update the readme to indicate that (1) `brew tap` has absorbed `brew any-tap` and (2) `brew any-tap` is broken.

**Comment by chdiza** [comment]
OK.

**Comment by chdiza** [comment]
> Propose the big idea (allowing non-git directories to be tapped).

I'm thinking about whether to pursue this idea further.  Maybe it's worth it, maybe not.  I do know, from experience with many proposals, that if the person doing the proposing is me, it will almost surely be rejected out of hand.  (This is one reason I'm loathe to modify Homebrew internals).

**Comment by telemachus** [comment]
> I'm thinking about whether to pursue this idea further. Maybe it's worth it, maybe not.

One other thought: float the idea in Homebrew's mailing list or in IRC. It might be a way to get some conversation started, hear from other people, discover problems (or benefits) we aren't thinking of.

**Pull request closed without merging**
